version: '3.8'

services:
  pubsub-emulator:
    image: gcr.io/google.com/cloudsdktool/cloud-sdk:latest
    command: gcloud beta emulators pubsub start --host-port=0.0.0.0:8085
    ports:
      - "8085:8085"

  springboot-app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - pubsub-emulator
    environment:
      PUBSUB_EMULATOR_HOST: pubsub-emulator:8085
